///////////////////////////////////////////////////////////
//  Biography.cs
//  Implementation of the Class Biography
//  Generated by Enterprise Architect
//  Created on:      05-okt-2021 21:42:29
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FamilyTree;
namespace FamilyTree {
	public class Biography : ObjekatSistema {

		private int idB;
		private string obrazovanje;
		private string radnoIskustvo;
		private string vjestine;

		public Biography(){

		}

		~Biography(){

		}

		public int IdB{
			get{
				return idB;
			}
			set{
				idB = value;
			}
		}

		public string Obrazovanje{
			get{
				return obrazovanje;
			}
			set{
				obrazovanje = value;
			}
		}

		public string RadnoIskustvo{
			get{
				return radnoIskustvo;
			}
			set{
				radnoIskustvo = value;
			}
		}

		public string Vjestine{
			get{
				return vjestine;
			}
			set{
				vjestine = value;
			}
		}

	}//end Biography

}//end namespace FamilyTree