///////////////////////////////////////////////////////////
//  Korisnikk.cs
//  Implementation of the Class Korisnikk
//  Generated by Enterprise Architect
//  Created on:      05-okt-2021 21:42:30
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FamilyTree;
namespace FamilyTree {
	public class Korisnikk : KorisnikOpis {

		public Korisnikk(){

		}

		~Korisnikk(){

		}

	}//end Korisnikk

}//end namespace FamilyTree