///////////////////////////////////////////////////////////
//  ObjekatSistema.cs
//  Implementation of the Class ObjekatSistema
//  Generated by Enterprise Architect
//  Created on:      05-okt-2021 21:42:30
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FamilyTree {
	public class ObjekatSistema {

		public ObjekatSistema(){

		}

		~ObjekatSistema(){

		}

	}//end ObjekatSistema

}//end namespace FamilyTree