///////////////////////////////////////////////////////////
//  IBaza.cs
//  Implementation of the Interface IBaza
//  Generated by Enterprise Architect
//  Created on:      06-okt-2021 14:41:29
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FamilyTree;
namespace FamilyTree {
	public interface IBaza  {

		IKonverzijaObjekta konverzija { get; set; }

		void Akcija();

		List<ObjekatSistema> listaObjekata{
			get;
			set;
		}
	}//end IBaza

}//end namespace FamilyTree