///////////////////////////////////////////////////////////
//  IzmijeniBiografija.cs
//  Implementation of the Class IzmijeniBiografija
//  Generated by Enterprise Architect
//  Created on:      06-okt-2021 14:41:29
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FamilyTree;
using System.Linq;

namespace FamilyTree {
	public class IzmijeniBiografija : TemplateIzmijeni 
	{

		private PristupBazi.BiografijaT bio;

		public IzmijeniBiografija(){}

		~IzmijeniBiografija(){}

		protected override void Izmijeni()
		{
			using (var db = new PristupBazi.DataBase())
			{
				if(bio != null)
				{
					db.BiografijaT.Remove(db.BiografijaT.Where(x => x.id == bio.id).First());
					db.BiografijaT.Add(bio);
					db.SaveChanges();
				}
			}
		}

		protected override void KonverzijaObjekatuModel()
		{
			konverzija = new StrategyKonverzijaBiografija();

			try
			{
				bio = (PristupBazi.BiografijaT)konverzija.objekatuModel(listaObjekata[0]);
			}
			catch
			{
				bio = null;
			}
		}


	}//end IzmijeniBiografija

}//end namespace FamilyTree