///////////////////////////////////////////////////////////
//  KomandaCitaj.cs
//  Implementation of the Class KomandaCitaj
//  Generated by Enterprise Architect
//  Created on:      06-okt-2021 14:41:29
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FamilyTree;
namespace FamilyTree {
	public class KomandaCitaj : OsobaKomanda {

		IKonverzijaObjekta konverzija = new StrategyKonverzijaOsoba();
		
		public List<ObjekatSistema> lista = new List<ObjekatSistema>();

		List<PristupBazi.OsobaT> osobe = new List<PristupBazi.OsobaT>();
		
		public KomandaCitaj(){}

		~KomandaCitaj(){}

		public override void Execute()
		{
			using(var db = new PristupBazi.DataBase())
			{
				foreach(var osoba in db.OsobaT)
				{
					osobe.Add(osoba);
				}
			}

			for( int i = 0; i < osobe.Count; i++)
			{
				ObjekatSistema obj = konverzija.modeluObjekat(osobe[i]);
				lista.Add(obj);
			}

		}

		public override void UnExecute(){}

	}//end KomandaCitaj

}//end namespace FamilyTree