///////////////////////////////////////////////////////////
//  KomandaIzmijeni.cs
//  Implementation of the Class KomandaIzmijeni
//  Generated by Enterprise Architect
//  Created on:      06-okt-2021 14:41:29
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FamilyTree;
using System.Linq;

namespace FamilyTree {
	public class KomandaIzmijeni : OsobaKomanda {

		public ObjekatSistema objekatPosle;
		public ObjekatSistema objekatPrije = new ObjekatSistema();

		IKonverzijaObjekta konverzija = new StrategyKonverzijaOsoba();
		IKonverzijaObjekta konverzijaBIO = new StrategyKonverzijaBiografija();
		public KomandaIzmijeni(){

		}

		~KomandaIzmijeni(){

		}

		public override void Execute()
		{
			using (var db = new PristupBazi.DataBase())
				try
				{

					PristupBazi.OsobaT obj = (PristupBazi.OsobaT)konverzija.objekatuModel(objekatPosle);
					PristupBazi.OsobaT pomocniObjekat = db.OsobaT.Where(x => x.id == obj.id).FirstOrDefault();
					objekatPrije = konverzija.modeluObjekat(pomocniObjekat);

					Person person = (Person)objekatPosle;

					PristupBazi.BiografijaT bio = (PristupBazi.BiografijaT)konverzijaBIO.objekatuModel(person.m_Biography);



					PristupBazi.BiografijaT pomocna = db.BiografijaT.Where(x => x.id == bio.id).FirstOrDefault();
					


					PristupBazi.OsobaT osoba = db.OsobaT.Where(x => x.id == obj.id).FirstOrDefault();

					
					db.OsobaT.Remove(osoba);
					db.BiografijaT.Remove(pomocna);
					db.SaveChanges();
					db.BiografijaT.Add(bio);
					obj.idB = bio.id;
					db.OsobaT.Add(obj);


					db.SaveChanges();
				}
				catch(Exception e)
				{

				}
			
		}
		

		public override void UnExecute()
		{
			using(var db = new PristupBazi.DataBase())
			{
				PristupBazi.OsobaT obj = (PristupBazi.OsobaT)konverzija.objekatuModel(objekatPrije);
				db.OsobaT.Remove(db.OsobaT.Where(x => x.id == obj.id).First());
				db.OsobaT.Add(obj);
				db.SaveChanges();
			}
		}

	}//end KomandaIzmijeni

}//end namespace FamilyTree