///////////////////////////////////////////////////////////
//  KomandaDodaj.cs
//  Implementation of the Class KomandaDodaj
//  Generated by Enterprise Architect
//  Created on:      06-okt-2021 14:41:29
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FamilyTree;
using System.Linq;

namespace FamilyTree {
	public class KomandaDodaj : OsobaKomanda {

		public ObjekatSistema objekatSistema;
		IKonverzijaObjekta konverzija = new StrategyKonverzijaOsoba();

		public KomandaDodaj(){}
		~KomandaDodaj(){}

		private int GetNextId()
		{
			int ret = -1;

			using (var db = new PristupBazi.DataBase())
			{
				ret = db.OsobaT.Max(x => x.id) + 1;
			}

			return ret;
		}

		public override void Execute()
		{
			((FamilyTree.Person)objekatSistema).IdP = this.GetNextId();

			using (var db = new PristupBazi.DataBase())
			{
				db.OsobaT.Add((PristupBazi.OsobaT)konverzija.objekatuModel(objekatSistema)); 
				db.SaveChanges();
			}
		}

		public override void UnExecute()
		{
			using(var db = new PristupBazi.DataBase())
			{
				PristupBazi.OsobaT obj = (PristupBazi.OsobaT)konverzija.objekatuModel(objekatSistema);
				db.OsobaT.Remove(db.OsobaT.Where(x => x.id == obj.id).First()); 
				db.SaveChanges();
			}
		}

	}//end KomandaDodaj

}//end namespace FamilyTree