///////////////////////////////////////////////////////////
//  ObrisiBiografija.cs
//  Implementation of the Class ObrisiBiografija
//  Generated by Enterprise Architect
//  Created on:      06-okt-2021 14:41:29
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FamilyTree;
using System.Linq;

namespace FamilyTree {
	public class ObrisiBiografija : TemplateObrisi {

		PristupBazi.BiografijaT obj;
		public ObrisiBiografija(){}

		~ObrisiBiografija(){}

		protected override void KonverzijaObjekatuModel()
		{
			konverzija = new StrategyKonverzijaBiografija();

			try
			{
				obj = (PristupBazi.BiografijaT)konverzija.objekatuModel(listaObjekata[0]);
			}
			catch
			{
				obj = null;
			}
		}

		protected override void Obrisi()
		{
			using(var db = new PristupBazi.DataBase())
			{
				if(obj!= null)
				{
					db.BiografijaT.Remove(db.BiografijaT.Where(x => x.id == obj.id).First());
					db.SaveChanges();
				}
			}
		}

	}//end ObrisiBiografija

}//end namespace FamilyTree