///////////////////////////////////////////////////////////
//  ObrisiKorisnik.cs
//  Implementation of the Class ObrisiKorisnik
//  Generated by Enterprise Architect
//  Created on:      06-okt-2021 14:41:29
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FamilyTree;
using System.Linq;

namespace FamilyTree {
	public class ObrisiKorisnik : TemplateObrisi {

		PristupBazi.KorisnikT obj;
		public ObrisiKorisnik(){

		}

		~ObrisiKorisnik(){

		}

		protected override void KonverzijaObjekatuModel()
		{
			konverzija = new StrategyKonverzijaKorisnik();
			try
			{
				obj = (PristupBazi.KorisnikT)konverzija.objekatuModel(listaObjekata[0]);
			}
			catch
			{
				obj = null;
			}
		}

		protected override void Obrisi()
		{
			using(var db = new PristupBazi.DataBase())
			{
				if (obj != null)
				{
					db.KorisnikT.Remove(db.KorisnikT.Where(x => x.id == obj.id).First());
					db.SaveChanges();
				}
			}
		}

	}//end ObrisiKorisnik

}//end namespace FamilyTree