///////////////////////////////////////////////////////////
//  ProcitajKorisnik.cs
//  Implementation of the Class ProcitajKorisnik
//  Generated by Enterprise Architect
//  Created on:      06-okt-2021 14:41:30
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FamilyTree;
using System.Linq;
using PristupBazi;

namespace FamilyTree {
	public class ProcitajKorisnik : TemplateProcitaj {

		List<PristupBazi.KorisnikT> korisnici = new List<PristupBazi.KorisnikT>();

		public ProcitajKorisnik(){}

		~ProcitajKorisnik(){}

		protected override void Citanje()
		{
			using(var db = new PristupBazi.DataBase())
			{
				foreach(var korisnik in db.KorisnikT)
				{
					korisnici.Add(korisnik);
				}
			}
		}


		protected override void KonverzijaModeluObjekat()
		{
			konverzija = new StrategyKonverzijaKorisnik();
			listaObjekata = new List<ObjekatSistema>(); 

			try
			{
				for(int i = 0; i < korisnici.Count(); i++)
				{
					ObjekatSistema obj = konverzija.modeluObjekat(korisnici[i]);
					listaObjekata.Add(obj);/// ne radi
				}

			}
			catch(Exception ex)
			{
				Console.WriteLine(ex);
				listaObjekata = null;
			}
		}


	}//end ProcitajKorisnik

}//end namespace FamilyTree