///////////////////////////////////////////////////////////
//  StrategyKonverzijaKorisnik.cs
//  Implementation of the Class StrategyKonverzijaKorisnik
//  Generated by Enterprise Architect
//  Created on:      06-okt-2021 14:41:30
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FamilyTree;
using PristupBazi;

namespace FamilyTree {
	public class StrategyKonverzijaKorisnik : IKonverzijaObjekta {

		public StrategyKonverzijaKorisnik(){}

		~StrategyKonverzijaKorisnik(){}

		public ObjekatSistema modeluObjekat(Model model){

			Korisnik korisnik = new Korisnik();
			KorisnikT korisnikT =(KorisnikT)model;

			korisnik.Ime = korisnikT.ime;
			korisnik.Prezime = korisnikT.prezime;
			korisnik.IdK = korisnikT.id;
			korisnik.Lozinka = korisnikT.lozinka;
			korisnik.Email = korisnikT.email;
			korisnik.Tip = (TipKorisnika)korisnikT.tip;

			return (ObjekatSistema)korisnik;
		}

		public Model objekatuModel(ObjekatSistema obj){

			KorisnikT korisnikT = new KorisnikT();
			Korisnik korisnik = (Korisnik)obj;

			korisnikT.ime = korisnik.Ime;
			korisnikT.prezime = korisnik.Prezime;
			korisnikT.id = korisnik.IdK;
			korisnikT.lozinka = korisnik.Lozinka;
			korisnikT.email = korisnik.Email;
			korisnikT.tip = (int)korisnik.Tip;

			return (Model)korisnikT;
		}

	}//end StrategyKonverzijaKorisnik

}//end namespace FamilyTree