///////////////////////////////////////////////////////////
//  StrategyKonverzijaBiografija.cs
//  Implementation of the Class StrategyKonverzijaBiografija
//  Generated by Enterprise Architect
//  Created on:      06-okt-2021 14:41:30
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FamilyTree;
using PristupBazi;
using System.Reflection;

namespace FamilyTree {
	public class StrategyKonverzijaBiografija : IKonverzijaObjekta
	{

		public StrategyKonverzijaBiografija(){}

		~StrategyKonverzijaBiografija(){}

		public ObjekatSistema modeluObjekat(Model model)
		{
			///biografijaT u objekatSistema Biografy
			Biography biography = new Biography();
			BiografijaT biografija = (BiografijaT)model;

			biography.IdB = biografija.id;
			biography.Obrazovanje = biografija.nivoObrazovanje;
			biography.RadnoIskustvo = biografija.iskustvo;
			biography.Vjestine = biografija.vjestine;

			return (ObjekatSistema)biography;
		}

		public Model objekatuModel(ObjekatSistema obj)
		{
			BiografijaT biografija = new BiografijaT();
			Biography biography = (Biography)obj;

			biografija.id = biography.IdB;
			biografija.iskustvo = biography.RadnoIskustvo;
			biografija.nivoObrazovanje = biography.Obrazovanje;
			biografija.vjestine = biography.Vjestine;

			return (Model)biografija;
		}

	}//end StrategyKonverzijaBiografija

}//end namespace FamilyTree