///////////////////////////////////////////////////////////
//  TemplateObrisi.cs
//  Implementation of the Class TemplateObrisi
//  Generated by Enterprise Architect
//  Created on:      06-okt-2021 14:41:30
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FamilyTree;
namespace FamilyTree {
	public abstract class TemplateObrisi : IBaza {

		public TemplateObrisi()
		{
			listaObjekata = new List<ObjekatSistema>();
		}

		~TemplateObrisi(){}

		public void Akcija()
		{
			KonverzijaObjekatuModel();
			Obrisi();
		}

		protected abstract void KonverzijaObjekatuModel();

		public List<ObjekatSistema> listaObjekata
		{
			get; set;
		}

		protected abstract void Obrisi();

		public IKonverzijaObjekta konverzija { get; set; }

	}//end TemplateObrisi

}//end namespace FamilyTree