///////////////////////////////////////////////////////////
//  TemplateDodaj.cs
//  Implementation of the Class TemplateDodaj
//  Generated by Enterprise Architect
//  Created on:      06-okt-2021 14:41:30
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FamilyTree;
using System.Linq;

namespace FamilyTree {
	public abstract class TemplateDodaj : IBaza {

		public TemplateDodaj(){
			listaObjekata = new List<ObjekatSistema>();
		}

		~TemplateDodaj(){}

		public void Akcija()
		{
			KonverzijaObjekatuModel();
			Dodaj();
		}

		protected abstract void Dodaj();

		protected abstract int NextId();
		

		protected abstract void KonverzijaObjekatuModel();

		public List<ObjekatSistema> listaObjekata{
			get;set;
		}

		public IKonverzijaObjekta konverzija { get ; set ; }   // zbog setovanja strategije u pod klasama za izmjene,dodavanja....
	}//end TemplateDodaj

}//end namespace FamilyTree