///////////////////////////////////////////////////////////
//  KorisnikOpis.cs
//  Implementation of the Class KorisnikOpis
//  Generated by Enterprise Architect
//  Created on:      05-okt-2021 21:42:30
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FamilyTree {
	public abstract class KorisnikOpis {

		public int id;

		public KorisnikOpis(){

		}

		~KorisnikOpis(){

		}

	}//end KorisnikOpis

}//end namespace FamilyTree