///////////////////////////////////////////////////////////
//  KorisnikAdapter.cs
//  Implementation of the Class KorisnikAdapter
//  Generated by Enterprise Architect
//  Created on:      05-okt-2021 21:42:29
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FamilyTree;
namespace FamilyTree {
	public class KorisnikAdapter : Sistem {

		public FamilyTree.Korisnikk m_Korisnikk;

		public KorisnikAdapter(){

		}

		~KorisnikAdapter(){

		}

		public override void logIn(){

		}

	}//end KorisnikAdapter

}//end namespace FamilyTree