///////////////////////////////////////////////////////////
//  Person.cs
//  Implementation of the Class Person
//  Generated by Enterprise Architect
//  Created on:      05-okt-2021 21:42:30
//  Original author: admin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FamilyTree;
namespace FamilyTree {
	public class Person : ObjekatSistema {

		private string adresa;
		private string brojTelefona;
		private string email;
		private int idP;
		private string ime;
		private string prezime;
		public FamilyTree.Person Parent;
		public FamilyTree.Person Child;
		public FamilyTree.Biography m_Biography;
		public FamilyTree.Person Spouse;

		public Person(){

		}

		~Person(){

		}

		public string Adresa{
			get{
				return adresa;
			}
			set{
				adresa = value;
			}
		}

		public string BrojTelefona{
			get{
				return brojTelefona;
			}
			set{
				brojTelefona = value;
			}
		}

		public string Email{
			get{
				return email;
			}
			set{
				email = value;
			}
		}

		public int IdP{
			get{
				return idP;
			}
			set{
				idP = value;
			}
		}

		public string Ime{
			get{
				return ime;
			}
			set{
				ime = value;
			}
		}

		public string Prezime{
			get{
				return prezime;
			}
			set{
				prezime = value;
			}
		}


	}//end Person

}//end namespace FamilyTree