///////////////////////////////////////////////////////////
//  Sistem.cs
//  Implementation of the Class Sistem
//  Generated by Enterprise Architect
//  Created on:      05-okt-2021 21:42:30
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FamilyTree {
	public abstract class Sistem {

		public string poruka;
		public TipDogadjaja tip;
		public DateTime vrijeme;

		public Sistem(){

		}

		~Sistem(){

		}

		public abstract void logIn();

	}//end Sistem

}//end namespace FamilyTree