///////////////////////////////////////////////////////////
//  TipDogadjaja.cs
//  Implementation of the Enumeration TipDogadjaja
//  Generated by Enterprise Architect
//  Created on:      05-okt-2021 21:42:30
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FamilyTree {
	public enum TipDogadjaja : int {

		DEBUG,
		INFO,
		ERROR,
		WARN,
		FATAL

	}//end TipDogadjaja

}//end namespace FamilyTree