///////////////////////////////////////////////////////////
//  TipKorisnika.cs
//  Implementation of the Enumeration TipKorisnika
//  Generated by Enterprise Architect
//  Created on:      05-okt-2021 21:42:30
//  Original author: AB
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FamilyTree {
	public enum TipKorisnika : int {

		Admin,
		Obican

	}//end TipKorisnika

}//end namespace FamilyTree